### ISSUE TITLE
Info file still references Drupal

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/matomo_reports#2]
The info file still references Drupal which is user-facing in the Project Manager.

> description = Adds Matomo reports to Drupal reports section.

https://github.com/backdrop-contrib/matomo_reports/blob/1.x-4.x/matomo_reports.info#L2

**Comment by oadaeh** [comment]
Thanks for creating this issue.
I have committed a fix to the dev branch, including a few other places where similar changes needed to be made.
